// Generated by gencpp from file demo01_action/addintsFeedback.msg
// DO NOT EDIT!


#ifndef DEMO01_ACTION_MESSAGE_ADDINTSFEEDBACK_H
#define DEMO01_ACTION_MESSAGE_ADDINTSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo01_action
{
template <class ContainerAllocator>
struct addintsFeedback_
{
  typedef addintsFeedback_<ContainerAllocator> Type;

  addintsFeedback_()
    : progress(0.0)  {
    }
  addintsFeedback_(const ContainerAllocator& _alloc)
    : progress(0.0)  {
  (void)_alloc;
    }



   typedef double _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::demo01_action::addintsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo01_action::addintsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct addintsFeedback_

typedef ::demo01_action::addintsFeedback_<std::allocator<void> > addintsFeedback;

typedef boost::shared_ptr< ::demo01_action::addintsFeedback > addintsFeedbackPtr;
typedef boost::shared_ptr< ::demo01_action::addintsFeedback const> addintsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo01_action::addintsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo01_action::addintsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo01_action::addintsFeedback_<ContainerAllocator1> & lhs, const ::demo01_action::addintsFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo01_action::addintsFeedback_<ContainerAllocator1> & lhs, const ::demo01_action::addintsFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo01_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo01_action::addintsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo01_action::addintsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo01_action::addintsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo01_action::addintsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo01_action::addintsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo01_action::addintsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo01_action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7afca0099e0cddc25243b1e3569895fe";
  }

  static const char* value(const ::demo01_action::addintsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7afca0099e0cddc2ULL;
  static const uint64_t static_value2 = 0x5243b1e3569895feULL;
};

template<class ContainerAllocator>
struct DataType< ::demo01_action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo01_action/addintsFeedback";
  }

  static const char* value(const ::demo01_action::addintsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo01_action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 progress\n"
;
  }

  static const char* value(const ::demo01_action::addintsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo01_action::addintsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addintsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo01_action::addintsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo01_action::addintsFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<double>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO01_ACTION_MESSAGE_ADDINTSFEEDBACK_H
